# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_FwNw6qNP9wYVmfNZnEL8PSabrlkcYC
"""

origin = list(map(int, input().split()))
go = list(map(int, input().split()))

distance = (origin[0] - go[0])**2 + (origin[1] - go[1])**2

if checkerboard[go[0]][go[1]] == 1:
  print("No")

elif distance == 1 or distance == 2:
  print("Yes")

else:
  print("No")